/*
 * This Scala source file was generated by the Gradle 'init' task.
 */
package day08

object App {
  def main(args: Array[String]): Unit = {
    println("test");
  }

  def greeting(): String = "Hello, world!"
}
