#!/bin/bash

set -e
cd "$(dirname $0)"

case $(uname -s) in
  Darwin)
    echo "==> Installing SWI-Prolog via Homebrew..."
    brew install swi-prolog
    ;;
  Linux)
    . /etc/os-release
    if [ "$ID_LIKE" == debian ]; then
      echo "==> Installing SWI-Prolog via APT..."
      sudo apt-get install -y swi-prolog
    else
      echo "Unsupported Linux distribution!"
      exit 1
    fi
    ;;
  *)
    echo "Unsupported OS!"
    exit 1
    ;;
esac

