#!/bin/bash

set -e
cd "$(dirname $0)"

case $(uname -s) in
  Darwin)
    echo "==> Installing Julia via Homebrew..."
    brew install --cask julia
    ;;
  Linux)
    echo "==> Setting up temporary directory for Julia download..."
    tmpdir="$(mktemp -d)"
    trap 'rm -rf -- "$tmpdir"' EXIT

    (
      cd "$tmpdir"

      echo "==> Downloading Julia..."
      archivename="julia-1.8.4-linux-x86_64.tar.gz"
      url="https://julialang-s3.julialang.org/bin/linux/x64/1.8/$archivename"
      curl -OL "$url"

      destdir="$HOME/opt/julia"
      echo "==> Installing Julia to $destdir..."
      mkdir -p "$destdir"
      tar -xvf "$archivename" -C "$destdir" --strip-components 1
    )
    ;;
  *)
    echo "Unsupported OS!"
    exit 1
    ;;
esac

echo "==> Installing project dependencies..."
julia --project=. -e "
using Pkg
Pkg.instantiate()
"
