#!/bin/sh

set -e
cd "$(dirname $0)/.."

if ! command -v gyb &>/dev/null; then
  echo "Please make sure to have the 'gyb' templating tool on your PATH!"
  echo "You can get it here: https://github.com/apple/swift/blob/main/utils/gyb.py"
  exit 1
fi

gyb -o README.md --line-directive "" README.md.gyb
