#!/bin/bash

set -e
cd "$(dirname $0)"

case $(uname -s) in
  Darwin)
    echo "==> Installing Python via Homebrew..."
    brew install python@3
    ;;
  Linux)
    if [ "$ID_LIKE" == debian ]; then
      echo "==> Installing Python via APT..."
      sudo apt-get install -y python3
    else
      echo "Unsupported Linux distribution!"
      exit 1
    fi
    ;;
  *)
    echo "Unsupported OS!"
    exit 1
    ;;
esac
