#!/bin/bash

set -e
cd "$(dirname $0)"

case $(uname -s) in
  Darwin)
    echo "==> Installing .NET via Homebrew..."
    brew install --cask dotnet
    ;;
  Linux)
    . /etc/os-release
    if [ "$ID_LIKE" == debian ]; then
      echo "==> Installing .NET via APT..."
      sudo apt-get install -y dotnet-sdk-6.0
    else
      echo "Unsupported Linux distribution!"
      exit 1
    fi
    ;;
  *)
    echo "Unsupported OS!"
    exit 1
    ;;
esac

