name: Run (Ubuntu)

on:
  push:

jobs:
  run:
    runs-on: ubuntu-latest
    name: Day ${{ matrix.day }}

    strategy:
      matrix:
        day: ['02', '03', '04', '05', '06', '07', '08', '09', '10', '11', '12', '13', '14', '15', '16', '17', '19', '21', '22', '23', '24', '25']

    steps:
    - uses: actions/checkout@v3
    - name: Bootstrap
      run: ./bootstrap
      working-directory: 'day${{ matrix.day }}'
    - name: Setup Env (if needed)
      run: '([ -x ./env ] && ./env >> "$GITHUB_ENV") || true'
      working-directory: 'day${{ matrix.day }}'
    - name: Setup PATH (if needed)
      run: '([ -x ./path ] && ./path >> "$GITHUB_PATH") || true'
      working-directory: 'day${{ matrix.day }}'
    - name: Run
      run: ./run
      working-directory: 'day${{ matrix.day }}'

