name: Run (macOS)

on:
  push:

jobs:
  run:
    runs-on: macos-latest
    name: Day ${{ matrix.day }}

    strategy:
      matrix:
        day: ['01', '20']

    steps:
    - uses: actions/checkout@v3
    - name: Bootstrap
      run: ./bootstrap
      working-directory: 'day${{ matrix.day }}'
    - name: Run
      run: ./run
      working-directory: 'day${{ matrix.day }}'

